#!/bin/bash

# Copyright (c) 2013-14 Duncan Eastoe <duncaneastoe@gmail.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, 
# modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the 
# Software is furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS 
# BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

function getHash {
    echo $($HASH_PROG "$1" | awk '{print $1}')
}

function parseArg {
    if [ -f "$1" ]; then
        local hash=$(getHash "$1")
        if [ "$hash" == "" ]; then
			echo "An error ocurred obtaining $HASH_PROG hash for $1"
			exit 1
		fi
		echo -e "$hash\n"
		eval ${2}="$hash"
    else
        eval ${2}="$1"
    fi
}

if [ ${#@} -lt 2 ]; then
    echo "Arguments:"
    echo "  [hash program] <file|hash> <file|hash>"
    exit 1
fi

if [ -z "$3" ]; then
	HASH_PROG="md5sum"
else
	HASH_PROG="$1"
	shift
fi

echo "Input: "$1
parseArg "$1" "input"

echo "Comparison: "$2
parseArg "$2" "comparison"

echo

if [ "$input" == "$comparison" ]; then
	echo "SUCCESS - hashes match"
	exit 0
else
	echo "FAILURE - hashes do not match!"
	exit 1
fi
