#!/bin/bash

# Copyright (c) 2013-14 Duncan Eastoe <duncaneastoe@gmail.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, 
# modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the 
# Software is furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS 
# BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.


function getMd5 {
    echo $(md5sum "$1" | awk '{print $1}')
}

function parseInput {
    if [ -f "$1" ]; then
        echo $(getMd5 "$1")
    else
        echo "$1"
    fi
}

if [ -z "$1" -o -z "$2" ]; then
    echo "Arguments:"
    echo "  <file> <file>"
    echo "  <file> <hash>"
    echo "  <hash> <file>"
    echo "  <hash> <hash>"
    exit 1
fi

echo "Input: "$1
echo "Comparison: "$2
echo

input=$(parseInput "$1")
comparison=$(parseInput "$2")

if [ "$input" == "$comparison" ]; then
	echo "SUCCESS - hashes match"
	exit 0
else
	echo "FAILURE - hashes do not match!"
	exit 1
fi


